### ISSUE TITLE
Missing event timestamps for Splunk Challenge 2

### ISSUE THREAD

**Issue by nfejes** [CSCI-4830-002-2014/challenge-week-3#7]
For Splunk Challenge 2, only 179 of the 300 events get their timestamp right. This can be seen by searching `sourcetype=course_github_events |stats count(created_at)`. All events get their timestamp right if `TRUNCATE=0` is added to the _Additional settings (overrides)_ under the _Advanced mode (props.conf)_ tab when setting up the data source.

**Comment by doubleshow** [comment]
It's okay some events don't get their timestamps right. By default it will use the timestamp from the previous event.

**Comment by nfejes** [comment]
Is it okay to use the correct values though? The graphs are somewhat different if you use them.

**Comment by doubleshow** [comment]
Yes. You can of course use correct values. It is just not a requirement to keep the challenge simpler.
