### ISSUE TITLE
Getting Data into a Form Splunk Can Recognize

### ISSUE THREAD

**Issue by ghost** [CSCI-4830-002-2014/challenge-week-3#9]
I have a question about challenge 1a for Splunk(III). For the field that we have to get right for the time stamp, is that one of the fields in the .json file that we got from Github? I've tried a lot of those fields, including multiple fields at once, and none of them have worked.

**Comment by doubleshow** [comment]
What fields have you tried?
On Thu, Sep 11, 2014 at 4:57 PM, cwitty1919 notifications@github.com wrote:I have a question about challenge 1a for Splunk(III). For the field that we have to get right for the time stamp, is that one of the fields in the .json file that we got from Github? I've tried a lot of those fields, including multiple fields at once, and none of them have worked.

**Comment by ghost** [comment]
id, type, actor (I have tried them separately and together). I looked further into the file and found the right field.

**Comment by doubleshow** [comment]
It sounds like you have resolved the issue.
